global using FluentResults;
global using ModelContextProtocol.Server;
global using System.ComponentModel;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using System.Text;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using TeamCityMcpTools.Models;
